# Generated by Django 3.2.2 on 2021-05-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('deadline', models.CharField(max_length=40)),
            ],
        ),
    ]
