# Generated by Django 3.2.2 on 2021-05-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_prompt_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_text_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.CharField(max_length=40)),
                ('txt_submit', models.CharField(max_length=100000)),
            ],
        ),
    ]
