# Generated by Django 3.2.2 on 2021-05-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_new_text_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='prompt_and_response_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_gen_time', models.DateTimeField()),
                ('the_prompt', models.CharField(max_length=150)),
                ('ai_response', models.CharField(max_length=10000)),
            ],
        ),
    ]
